files:
- generatedChecksum: 46603BAEE159F18E57B4F158B6F09E7B
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: datastreamer_UART_sam.c
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 46603BAEE159F18E57B4F158B6F09E7B
- generatedChecksum: E45D1648EFC10229D7BE94DB19221FF7
  logicalPath: config\sam_d20_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E45D1648EFC10229D7BE94DB19221FF7
- generatedChecksum: B455DD3F48E1FD7641D72CE54403B918
  logicalPath: config\sam_d20_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B455DD3F48E1FD7641D72CE54403B918
- generatedChecksum: EDE43F9221220C878A5B9CEE41A65CF4
  logicalPath: config\sam_d20_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EDE43F9221220C878A5B9CEE41A65CF4
- generatedChecksum: 6513F2461B8F476B68CA73906086047F
  logicalPath: config\sam_d20_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6513F2461B8F476B68CA73906086047F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: F97568E5714F820D89F62AA4CD405765
  logicalPath: config\sam_d20_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: F97568E5714F820D89F62AA4CD405765
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_d20_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: 8FE5490B8E7689B5B921419CF2BE297D
  logicalPath: config\sam_d20_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8FE5490B8E7689B5B921419CF2BE297D
- generatedChecksum: 4924A39380F3BDF3EE769570743C460D
  logicalPath: config\sam_d20_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4924A39380F3BDF3EE769570743C460D
- generatedChecksum: B1301FE4E2FE570ED9FE3B9983E66481
  logicalPath: config\sam_d20_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: B1301FE4E2FE570ED9FE3B9983E66481
- generatedChecksum: 9EC1182767AFF702BE209DC487D07162
  logicalPath: config\sam_d20_xpro\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9EC1182767AFF702BE209DC487D07162
- generatedChecksum: 160666765902D835EDECC5EB91D6CDDF
  logicalPath: config\sam_d20_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 160666765902D835EDECC5EB91D6CDDF
- generatedChecksum: 2645E564BD945DAED1424FD8D7B39330
  logicalPath: config\sam_d20_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2645E564BD945DAED1424FD8D7B39330
- generatedChecksum: E9D826A71CCBA17B45EE8E83BA3276AB
  logicalPath: config\sam_d20_xpro\touch
  name: touch.c
  physicalPath: touch
  security: NON_SECURE
  type: SOURCE
  userChecksum: E9D826A71CCBA17B45EE8E83BA3276AB
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\sam_d20_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: C90096E1F900F7C19A1751188E3A8E32
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.db
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: C90096E1F900F7C19A1751188E3A8E32
- generatedChecksum: 696D18869D552C0F6F8591673EEF593C
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.ds
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 696D18869D552C0F6F8591673EEF593C
- generatedChecksum: DD2922E89ECE8DB338D63C81A090A09E
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.sc
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: DD2922E89ECE8DB338D63C81A090A09E
- generatedChecksum: 61614A3B65482ED7F8C8A87E871DAE3A
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 61614A3B65482ED7F8C8A87E871DAE3A
- generatedChecksum: DBC71687C01AED1E449ED8B829D68D75
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DBC71687C01AED1E449ED8B829D68D75
- generatedChecksum: 7B4B4106EDCDDAB2C07167B44A11708D
  logicalPath: packs\ATSAMD20J18_DFP
  name: atsamd20j18.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B4B4106EDCDDAB2C07167B44A11708D
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: EF7C3C5918A153FC7CB8C785309F1F42
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EF7C3C5918A153FC7CB8C785309F1F42
- generatedChecksum: 9370572AD402AB9E975F0FDC2266795F
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: datastreamer.h
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9370572AD402AB9E975F0FDC2266795F
- generatedChecksum: 85B1C9DD5D8D4F37E702A388970B1D13
  logicalPath: config\sam_d20_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85B1C9DD5D8D4F37E702A388970B1D13
- generatedChecksum: EBE4EB7842A4289C2AC1C0D28EF5AD67
  logicalPath: config\sam_d20_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: EBE4EB7842A4289C2AC1C0D28EF5AD67
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d20_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: DF73F1FD406128CFF6DCDCF17B582138
  logicalPath: config\sam_d20_xpro
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: DF73F1FD406128CFF6DCDCF17B582138
- generatedChecksum: F7E9546F7C4EFD53476AA132B069BC26
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F7E9546F7C4EFD53476AA132B069BC26
- generatedChecksum: 23236B108D96C78FC087DE9F46329431
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 23236B108D96C78FC087DE9F46329431
- generatedChecksum: 27F1A8D568DC6E31B9FC9F133335B831
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 27F1A8D568DC6E31B9FC9F133335B831
- generatedChecksum: C9C0FCAB478A35649A2BA7BDBD3CBA30
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C9C0FCAB478A35649A2BA7BDBD3CBA30
- generatedChecksum: B06A7E2E53689A0BBD537D2D33717226
  logicalPath: config\sam_d20_xpro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B06A7E2E53689A0BBD537D2D33717226
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: 67F97FC39C2B50A1D0FC7E8E6CF00C6D
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 67F97FC39C2B50A1D0FC7E8E6CF00C6D
- generatedChecksum: A1DEB7F98ED9B61451CE5969BB69C4E2
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A1DEB7F98ED9B61451CE5969BB69C4E2
- generatedChecksum: D9883C70E96468DEE4D7B4669D1C837B
  logicalPath: config\sam_d20_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: D9883C70E96468DEE4D7B4669D1C837B
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d20_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_d20_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: 71D16914F1E580B0AF77141622DCD865
  logicalPath: config\sam_d20_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 71D16914F1E580B0AF77141622DCD865
- generatedChecksum: FE51A9DF504C4F93F293285C41E122A1
  logicalPath: config\sam_d20_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: FE51A9DF504C4F93F293285C41E122A1
- generatedChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
  logicalPath: config\sam_d20_xpro\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
- generatedChecksum: DCC0369AFDD597FB63203FB1B7488E8B
  logicalPath: config\sam_d20_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: DCC0369AFDD597FB63203FB1B7488E8B
- generatedChecksum: 6F7C32BEA82BE8985E2B44B601498B7C
  logicalPath: config\sam_d20_xpro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 6F7C32BEA82BE8985E2B44B601498B7C
- generatedChecksum: 04C8E3C2A27856229F9387BED9467911
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 04C8E3C2A27856229F9387BED9467911
- generatedChecksum: AB9C19CB3D1C202CE9ED1C4D2A8B3DB6
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AB9C19CB3D1C202CE9ED1C4D2A8B3DB6
- generatedChecksum: 8F5153CF14498A1492E057678BE86F0F
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F5153CF14498A1492E057678BE86F0F
- generatedChecksum: 55FAD416646C70456CC8F553E19EEA94
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_acq_samd20_0x000e_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 55FAD416646C70456CC8F553E19EEA94
- generatedChecksum: 7DEFA02F559ACE61891DB528BF24E326
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_common_components_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DEFA02F559ACE61891DB528BF24E326
- generatedChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_freq_hop_auto_0x0004_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
- generatedChecksum: FB86752FE87F6FFC05CA323960F53142
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_scroller_0x000b_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: FB86752FE87F6FFC05CA323960F53142
- generatedChecksum: B40B26CBF970F40A2CB63C74002B65D4
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_touch_key_0x0002_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: B40B26CBF970F40A2CB63C74002B65D4
- generatedChecksum: 7E3018CE00C07DD04076D474C2C8E201
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7E3018CE00C07DD04076D474C2C8E201
- generatedChecksum: 895AAF57F8BB10F1CF05A197AF51D20E
  logicalPath: packs\ATSAMD20J18_DFP\pio
  name: samd20j18.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 895AAF57F8BB10F1CF05A197AF51D20E
- generatedChecksum: BF83964046BC16326781DC33DB004B7B
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BF83964046BC16326781DC33DB004B7B
- generatedChecksum: 8F8BAA01E847D7C106FDDF03F0735423
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F8BAA01E847D7C106FDDF03F0735423
- generatedChecksum: 69A268C7263485C322910EEFA8D97B5E
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 69A268C7263485C322910EEFA8D97B5E
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d20_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: F4A700BDACFCE69A996C2250DCF60FFF
  logicalPath: config\sam_d20_xpro\touch
  name: touch.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: F4A700BDACFCE69A996C2250DCF60FFF
- generatedChecksum: 6D4F4B6BDDCFAAB2A42B4CC277DF3E91
  logicalPath: config\sam_d20_xpro\touch
  name: touch_api_ptc.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 6D4F4B6BDDCFAAB2A42B4CC277DF3E91
- generatedChecksum: A102ED238794D81B3B354DBD9D8978FD
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A102ED238794D81B3B354DBD9D8978FD
- generatedChecksum: A24C9818BE52278D08A208C324917009
  logicalPath: config\sam_d20_xpro
  name: ATSAMD20J18.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: A24C9818BE52278D08A208C324917009
format_version: v1.0
libraries:
- name: qtm_acq_samd20_0x000e.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_touch_key_cm0p_0x0002.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_scroller_cm0p_0x000b.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_freq_hop_auto_cm0p_0x0004.X.a
  path: /touch/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d20_xpro;../src/packs/ATSAMD20J18_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d20_xpro;../src/packs/ATSAMD20J18_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
