configName: sam_d20_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMD20J18
projectName: ''
settings:
  PackageFilter: bsp;core;csp;quick_docs;touch;touch_apps;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD20_DFP\3.4.68\samd20\atdf\ATSAMD20J18.atdf
