configName: pic32cmjh_curiosity_pro
folderName: pic32cmjh_curiosity_pro
format_version: v1.0
frameworkPath: C:\Users\i41646\.mcc\libraries\HarmonyContent
processor: PIC32CM5164JH01100
projectName: pic32cmjh_curiosity_pro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CM-JH_DFP\1.0.80\PIC32CM-JH01\atdf\PIC32CM5164JH01100.atdf
