format_version: v1.0
type: UniqueComponent
attributes: {id: lib_qtouch}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: DEF_NOD_AKS2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: DEF_NOD_AKS3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: DEF_NOD_AKS4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: DEF_SCR_TYPE0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: DEF_SENSOR_DET_THRESHOLD0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '60'}
  - type: Integer
    attributes: {id: DEF_SENSOR_DET_THRESHOLD1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '60'}
  - type: Integer
    attributes: {id: DEF_SENSOR_DET_THRESHOLD2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '40'}
  - type: Integer
    attributes: {id: DEF_SENSOR_DET_THRESHOLD3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '40'}
  - type: Integer
    attributes: {id: DEF_SENSOR_DET_THRESHOLD4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '40'}
  - type: Boolean
    attributes: {id: ENABLE_DATA_STREAMER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_FREQ_HOP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ENABLE_SCROLLER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: FREQ_AUTOTUNE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: MUTL-X-INPUT_0}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: X0  (PA08), value: X_NONE, key: '0'}
          - type: Pair
            attributes: {description: X1  (PA09), value: X(1), key: '1'}
          - type: Pair
            attributes: {description: X2  (PA10), value: X(2), key: '2'}
          - type: Pair
            attributes: {description: X3  (PA11), value: X(3), key: '3'}
          - type: Pair
            attributes: {description: X4  (PA16), value: X(4), key: '4'}
          - type: Pair
            attributes: {description: X5  (PA17), value: X(5), key: '5'}
          - type: Pair
            attributes: {description: X6  (PA18), value: X(6), key: '6'}
          - type: Pair
            attributes: {description: X7  (PA19), value: X(7), key: '7'}
          - type: Pair
            attributes: {description: X8  (PA20), value: X(8), key: '8'}
          - type: Pair
            attributes: {description: X9  (PA21), value: X(9), key: '9'}
          - type: Pair
            attributes: {description: X10  (PA22), value: X(10), key: '10'}
          - type: Pair
            attributes: {description: X11  (PA23), value: X(11), key: '11'}
          - type: Pair
            attributes: {description: X12  (PB12), value: X(12), key: '12'}
          - type: Pair
            attributes: {description: X13  (PB13), value: X(13), key: '13'}
          - type: Pair
            attributes: {description: X14  (PB14), value: X(14), key: '14'}
          - type: Pair
            attributes: {description: X15  (PB15), value: X(15), key: '15'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '0'}
  - type: KeyValueSet
    attributes: {id: MUTL-X-INPUT_1}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: X0  (PA08), value: X(0), key: '0'}
          - type: Pair
            attributes: {description: X1  (PA09), value: X_NONE, key: '1'}
          - type: Pair
            attributes: {description: X2  (PA10), value: X(2), key: '2'}
          - type: Pair
            attributes: {description: X3  (PA11), value: X(3), key: '3'}
          - type: Pair
            attributes: {description: X4  (PA16), value: X(4), key: '4'}
          - type: Pair
            attributes: {description: X5  (PA17), value: X(5), key: '5'}
          - type: Pair
            attributes: {description: X6  (PA18), value: X(6), key: '6'}
          - type: Pair
            attributes: {description: X7  (PA19), value: X(7), key: '7'}
          - type: Pair
            attributes: {description: X8  (PA20), value: X(8), key: '8'}
          - type: Pair
            attributes: {description: X9  (PA21), value: X(9), key: '9'}
          - type: Pair
            attributes: {description: X10  (PA22), value: X(10), key: '10'}
          - type: Pair
            attributes: {description: X11  (PA23), value: X(11), key: '11'}
          - type: Pair
            attributes: {description: X12  (PB12), value: X(12), key: '12'}
          - type: Pair
            attributes: {description: X13  (PB13), value: X(13), key: '13'}
          - type: Pair
            attributes: {description: X14  (PB14), value: X(14), key: '14'}
          - type: Pair
            attributes: {description: X15  (PB15), value: X(15), key: '15'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '1'}
  - type: KeyValueSet
    attributes: {id: MUTL-X-INPUT_2}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: X0  (PA08), value: X(0), key: '0'}
          - type: Pair
            attributes: {description: X1  (PA09), value: X(1), key: '1'}
          - type: Pair
            attributes: {description: X2  (PA10), value: X_NONE, key: '2'}
          - type: Pair
            attributes: {description: X3  (PA11), value: X(3), key: '3'}
          - type: Pair
            attributes: {description: X4  (PA16), value: X(4), key: '4'}
          - type: Pair
            attributes: {description: X5  (PA17), value: X(5), key: '5'}
          - type: Pair
            attributes: {description: X6  (PA18), value: X(6), key: '6'}
          - type: Pair
            attributes: {description: X7  (PA19), value: X(7), key: '7'}
          - type: Pair
            attributes: {description: X8  (PA20), value: X(8), key: '8'}
          - type: Pair
            attributes: {description: X9  (PA21), value: X(9), key: '9'}
          - type: Pair
            attributes: {description: X10  (PA22), value: X(10), key: '10'}
          - type: Pair
            attributes: {description: X11  (PA23), value: X(11), key: '11'}
          - type: Pair
            attributes: {description: X12  (PB12), value: X(12), key: '12'}
          - type: Pair
            attributes: {description: X13  (PB13), value: X(13), key: '13'}
          - type: Pair
            attributes: {description: X14  (PB14), value: X(14), key: '14'}
          - type: Pair
            attributes: {description: X15  (PB15), value: X(15), key: '15'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '2'}
  - type: KeyValueSet
    attributes: {id: MUTL-X-INPUT_3}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: X0  (PA08), value: X(0), key: '0'}
          - type: Pair
            attributes: {description: X1  (PA09), value: X(1), key: '1'}
          - type: Pair
            attributes: {description: X2  (PA10), value: X(2), key: '2'}
          - type: Pair
            attributes: {description: X3  (PA11), value: X_NONE, key: '3'}
          - type: Pair
            attributes: {description: X4  (PA16), value: X(4), key: '4'}
          - type: Pair
            attributes: {description: X5  (PA17), value: X(5), key: '5'}
          - type: Pair
            attributes: {description: X6  (PA18), value: X(6), key: '6'}
          - type: Pair
            attributes: {description: X7  (PA19), value: X(7), key: '7'}
          - type: Pair
            attributes: {description: X8  (PA20), value: X(8), key: '8'}
          - type: Pair
            attributes: {description: X9  (PA21), value: X(9), key: '9'}
          - type: Pair
            attributes: {description: X10  (PA22), value: X(10), key: '10'}
          - type: Pair
            attributes: {description: X11  (PA23), value: X(11), key: '11'}
          - type: Pair
            attributes: {description: X12  (PB12), value: X(12), key: '12'}
          - type: Pair
            attributes: {description: X13  (PB13), value: X(13), key: '13'}
          - type: Pair
            attributes: {description: X14  (PB14), value: X(14), key: '14'}
          - type: Pair
            attributes: {description: X15  (PB15), value: X(15), key: '15'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '3'}
  - type: KeyValueSet
    attributes: {id: MUTL-X-INPUT_4}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: X0  (PA08), value: X(0), key: '0'}
          - type: Pair
            attributes: {description: X1  (PA09), value: X(1), key: '1'}
          - type: Pair
            attributes: {description: X2  (PA10), value: X(2), key: '2'}
          - type: Pair
            attributes: {description: X3  (PA11), value: X(3), key: '3'}
          - type: Pair
            attributes: {description: X4  (PA16), value: X_NONE, key: '4'}
          - type: Pair
            attributes: {description: X5  (PA17), value: X(5), key: '5'}
          - type: Pair
            attributes: {description: X6  (PA18), value: X(6), key: '6'}
          - type: Pair
            attributes: {description: X7  (PA19), value: X(7), key: '7'}
          - type: Pair
            attributes: {description: X8  (PA20), value: X(8), key: '8'}
          - type: Pair
            attributes: {description: X9  (PA21), value: X(9), key: '9'}
          - type: Pair
            attributes: {description: X10  (PA22), value: X(10), key: '10'}
          - type: Pair
            attributes: {description: X11  (PA23), value: X(11), key: '11'}
          - type: Pair
            attributes: {description: X12  (PB12), value: X(12), key: '12'}
          - type: Pair
            attributes: {description: X13  (PB13), value: X(13), key: '13'}
          - type: Pair
            attributes: {description: X14  (PB14), value: X(14), key: '14'}
          - type: Pair
            attributes: {description: X15  (PB15), value: X(15), key: '15'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '4'}
  - type: KeyValueSet
    attributes: {id: SELFCAP-INPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: KeyValueSet
    attributes: {id: SELFCAP-INPUT_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: KeyValueSet
    attributes: {id: SELFCAP-INPUT_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '11'}
  - type: KeyValueSet
    attributes: {id: SELFCAP-INPUT_3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: KeyValueSet
    attributes: {id: SELFCAP-INPUT_4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '13'}
  - type: Integer
    attributes: {id: TOUCH_CHAN_ENABLE_CNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER_db}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER_ds}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER_sc}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_CH_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_CH_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_CH_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_CH_3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_CH_4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_KEY_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_KEY_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_KEY_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_KEY_3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_KEY_4}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_SCROLLER_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: TOUCH_HOP_AUTO_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Library
    attributes: {id: TOUCH_HOP_AUTO_LIB}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TOUCH_KEY_ENABLE_CNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Boolean
    attributes: {id: TOUCH_LOADED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: TOUCH_LOADED, value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_PRE_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: TOUCH_PRE_GENERATE, value: 'true'}
  - type: Integer
    attributes: {id: TOUCH_SCROLLER_ENABLE_CNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: TOUCH_SCR_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Library
    attributes: {id: TOUCH_SCR_LIB}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TOUCH_SCR_START_KEY0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: String
    attributes: {id: TOUCH_SERCOM_INSTANCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: SERCOM3}
  - type: String
    attributes: {id: TOUCH_TIMER_INSTANCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: RTC}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Touch_sercom}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom3}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM3_UART}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectDependency
    attributes: {id: Touch_timer}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: rtc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: RTC_TMR}
- type: ElementPosition
  attributes: {x: '315', y: '233', id: lib_qtouch}
