format_version: v1.0
type: UniqueComponent
attributes: {id: lib_qtouch}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: DEF_NOD_PTC_PRESCALER0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: DEF_SENSOR_DET_THRESHOLD0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '225'}
  - type: Boolean
    attributes: {id: ENABLE_DATA_STREAMER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: ENABLE_SCROLLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: 'false'}
  - type: Boolean
    attributes: {id: ENABLE_TOUCH_TUNE_WITH_PLUGIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: LOW_POWER_KEYS_MASK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '0x0'}
  - type: String
    attributes: {id: MUTL_4P_AGAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: GAIN_1}
  - type: String
    attributes: {id: MUTL_4P_CSD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '0'}
  - type: String
    attributes: {id: MUTL_4P_DGAIN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: GAIN_1}
  - type: String
    attributes: {id: MUTL_4P_FL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: FILTER_LEVEL_16}
  - type: String
    attributes: {id: MUTL_4P_NODE_KEY_MAP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '0'}
  - type: Integer
    attributes: {id: MUTL_4P_NUM_GROUP}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '1'}
  - type: String
    attributes: {id: MUTL_4P_PRSC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: PRSC_DIV_SEL_4}
  - type: String
    attributes: {id: MUTL_4P_X_LINE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: '{ X(0),X_NONE,X_NONE,X_NONE }'}
  - type: String
    attributes: {id: MUTL_4P_Y_LINE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: Y(0)}
  - type: String
    attributes: {id: MUTL_4P_Y_RES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: RSEL_VAL_0}
  - type: String
    attributes: {id: PTC_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: GCLK_ID_31_FREQ}
  - type: KeyValueSet
    attributes: {id: SELFCAP-INPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '30'}
  - type: KeyValueSet
    attributes: {id: SENSE_TECHNOLOGY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: TOUCH_CHAN_ENABLE_CNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER_db}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER_ds}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_HEADER_sc}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: TOUCH_DATA_STREAMER_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_CH_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_ENABLE_KEY_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: TOUCH_KEY_ENABLE_CNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: TOUCH_LOADED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TOUCH_PRE_GENERATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: TOUCH_SCRIPT_EVENT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: ''}
  - type: String
    attributes: {id: TOUCH_SERCOM_INSTANCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: TOUCH_SERCOM_KRONO_INSTANCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: SERCOM3}
  - type: String
    attributes: {id: TOUCH_TIMER_INSTANCE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_qtouch, value: RTC}
  - type: File
    attributes: {id: TOUCH_TUNE_WITH_PLUGIN_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: TOUCH_TUNE_WITH_PLUGIN_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Touch_sercom}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: Touch_sercom_Krono}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom3}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM3_UART}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectDependency
    attributes: {id: Touch_timer}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: rtc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: RTC_TMR}
  - type: DirectDependency
    attributes: {id: lib_acquire}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: ptc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: ptc_Acq_Engine}
- type: ElementPosition
  attributes: {x: '466', y: '229', id: lib_qtouch}
