files:
- generatedChecksum: F80AAB27611709334D6B0CAA62A27980
  logicalPath: config\sam_d11_xpro\touch\datastreamer
  name: datastreamer_UART_sam.c
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F80AAB27611709334D6B0CAA62A27980
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_d11_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: 5647482ADBDFBD1A8AD79F164A9D63B7
  logicalPath: config\sam_d11_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5647482ADBDFBD1A8AD79F164A9D63B7
- generatedChecksum: 6F51B88091980500BE2E9FD16B162784
  logicalPath: config\sam_d11_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6F51B88091980500BE2E9FD16B162784
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_d11_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: C2231A2E5C61A61C9C621BA8E2F87181
  logicalPath: config\sam_d11_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2231A2E5C61A61C9C621BA8E2F87181
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_d11_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: C01556A578C620EE96855774B53E7468
  logicalPath: config\sam_d11_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C01556A578C620EE96855774B53E7468
- generatedChecksum: 13B753618E67BC2B344224816DCBACFE
  logicalPath: config\sam_d11_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13B753618E67BC2B344224816DCBACFE
- generatedChecksum: 971816F1D363086EC679902A5C5E05D4
  logicalPath: config\sam_d11_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 971816F1D363086EC679902A5C5E05D4
- generatedChecksum: 4A6615DF1E16F5596924C3F084CF76F1
  logicalPath: config\sam_d11_xpro\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4A6615DF1E16F5596924C3F084CF76F1
- generatedChecksum: 0E0B96B4EB2AE8B53DD6859E129553D8
  logicalPath: config\sam_d11_xpro\peripheral\sercom\usart
  name: plib_sercom0_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E0B96B4EB2AE8B53DD6859E129553D8
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_d11_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: 5F593A17157F6FA4D958CDC1990BC4D5
  logicalPath: config\sam_d11_xpro\touch
  name: touch.c
  physicalPath: touch
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5F593A17157F6FA4D958CDC1990BC4D5
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\sam_d11_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 2677B75DC09987BC595D5CD3F171CD1E
  logicalPath: config\sam_d11_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.db
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 2677B75DC09987BC595D5CD3F171CD1E
- generatedChecksum: 2F34EA64D89C9608E1C53A76B60F0EBB
  logicalPath: config\sam_d11_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.ds
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 2F34EA64D89C9608E1C53A76B60F0EBB
- generatedChecksum: 3943BB38ED6CB578D5D572DE0FF5C1BE
  logicalPath: config\sam_d11_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.sc
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 3943BB38ED6CB578D5D572DE0FF5C1BE
- generatedChecksum: 4DD9DBA759EF7DE2B25FFA72B25DDCD0
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4DD9DBA759EF7DE2B25FFA72B25DDCD0
- generatedChecksum: E1B99CC25B1B91A0DEE836277D28A4FA
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E1B99CC25B1B91A0DEE836277D28A4FA
- generatedChecksum: 8A5EAC261D722FCAD0FA60A3FD237D80
  logicalPath: packs\ATSAMD11D14AM_DFP
  name: atsamd11d14am.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 8A5EAC261D722FCAD0FA60A3FD237D80
- generatedChecksum: 1D1E89E5594EE4FC269A9D502F04A4BA
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D1E89E5594EE4FC269A9D502F04A4BA
- generatedChecksum: 9370572AD402AB9E975F0FDC2266795F
  logicalPath: config\sam_d11_xpro\touch\datastreamer
  name: datastreamer.h
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9370572AD402AB9E975F0FDC2266795F
- generatedChecksum: B2B4041A724E2C7DC1D6AB08F263D147
  logicalPath: config\sam_d11_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B2B4041A724E2C7DC1D6AB08F263D147
- generatedChecksum: EB6CBB005396A0ECE2672D3ACA42FFAF
  logicalPath: config\sam_d11_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: EB6CBB005396A0ECE2672D3ACA42FFAF
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d11_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: C0A96DDBC894A73CAA8493B832DCE172
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C0A96DDBC894A73CAA8493B832DCE172
- generatedChecksum: 9CD6896C4584CB0CD2EB1CB4BFF679CE
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9CD6896C4584CB0CD2EB1CB4BFF679CE
- generatedChecksum: 714CFEAD5DEFE1FC12938565CA191502
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 714CFEAD5DEFE1FC12938565CA191502
- generatedChecksum: AD996FC2C09B7A77436F67D4C6D71ADD
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AD996FC2C09B7A77436F67D4C6D71ADD
- generatedChecksum: 642C03C9EEE3F771393405FE4603F24B
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 642C03C9EEE3F771393405FE4603F24B
- generatedChecksum: 5A6D893A2F207140E84ABAB17DC8B5DB
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A6D893A2F207140E84ABAB17DC8B5DB
- generatedChecksum: 4D95F71D71F0A56D9ED955A1B790BF7B
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D95F71D71F0A56D9ED955A1B790BF7B
- generatedChecksum: 2E0CDE2EFB6FDAC165B5DCA2DCB79327
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2E0CDE2EFB6FDAC165B5DCA2DCB79327
- generatedChecksum: 9AA552EAC09D968E3E6EA5F42B2D40A1
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9AA552EAC09D968E3E6EA5F42B2D40A1
- generatedChecksum: 729DB333FDDAD65AB9172F82E0E143D3
  logicalPath: config\sam_d11_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: 729DB333FDDAD65AB9172F82E0E143D3
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d11_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_d11_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: D39664ECFA43A34431A127602F3A82ED
  logicalPath: config\sam_d11_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: D39664ECFA43A34431A127602F3A82ED
- generatedChecksum: 4A3692FE82B14820DA86221209A3126A
  logicalPath: config\sam_d11_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 4A3692FE82B14820DA86221209A3126A
- generatedChecksum: 83D5545FF9C0CDB228311D678EB175DE
  logicalPath: config\sam_d11_xpro\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 83D5545FF9C0CDB228311D678EB175DE
- generatedChecksum: 9E847139EB4A35248CEAA3CF830D18DD
  logicalPath: config\sam_d11_xpro\peripheral\sercom\usart
  name: plib_sercom0_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E847139EB4A35248CEAA3CF830D18DD
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_d11_xpro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: CF4E7113CFA90E0E0B7F06FC9730AFE8
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CF4E7113CFA90E0E0B7F06FC9730AFE8
- generatedChecksum: 9F9E6DD3465FBDA1F06C3B55888F5352
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F9E6DD3465FBDA1F06C3B55888F5352
- generatedChecksum: 667C79C2C8EDEAA14FF30B7A52CE96F0
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 667C79C2C8EDEAA14FF30B7A52CE96F0
- generatedChecksum: 50442CD77906A8E47B90ED5749D5AEB7
  logicalPath: config\sam_d11_xpro\touch
  name: qtm_acq_samd1x_0x0009_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 50442CD77906A8E47B90ED5749D5AEB7
- generatedChecksum: 7DEFA02F559ACE61891DB528BF24E326
  logicalPath: config\sam_d11_xpro\touch
  name: qtm_common_components_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DEFA02F559ACE61891DB528BF24E326
- generatedChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
  logicalPath: config\sam_d11_xpro\touch
  name: qtm_freq_hop_auto_0x0004_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
- generatedChecksum: B40B26CBF970F40A2CB63C74002B65D4
  logicalPath: config\sam_d11_xpro\touch
  name: qtm_touch_key_0x0002_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: B40B26CBF970F40A2CB63C74002B65D4
- generatedChecksum: 7A78E895A6FAA7C4097AD69AF1D35310
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A78E895A6FAA7C4097AD69AF1D35310
- generatedChecksum: 441E252001BD1FA8446E023B732F93EC
  logicalPath: packs\ATSAMD11D14AM_DFP\pio
  name: samd11d14am.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 441E252001BD1FA8446E023B732F93EC
- generatedChecksum: 0FF1D283F2F0858A158B569EFE2AD049
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0FF1D283F2F0858A158B569EFE2AD049
- generatedChecksum: 9B7EC9BF1EADF4CB6C6AFFB0D2F48F96
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B7EC9BF1EADF4CB6C6AFFB0D2F48F96
- generatedChecksum: CECF410F86CB5F14CC1B703DFB26080F
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CECF410F86CB5F14CC1B703DFB26080F
- generatedChecksum: EDBCDE8C947DB3E66655F87A2B456BA4
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EDBCDE8C947DB3E66655F87A2B456BA4
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d11_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 69284F2E8B974622325B869C67567B47
  logicalPath: config\sam_d11_xpro\touch
  name: touch.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 69284F2E8B974622325B869C67567B47
- generatedChecksum: F3954BDE2CD16ADAE0BB12E9FF1E1D73
  logicalPath: config\sam_d11_xpro\touch
  name: touch_api_ptc.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: F3954BDE2CD16ADAE0BB12E9FF1E1D73
- generatedChecksum: 87393BF9ECA53228BFD27FC578294183
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 87393BF9ECA53228BFD27FC578294183
- generatedChecksum: 7ACDFC92FD15ECFBF7D14D1E2E6A4A9F
  logicalPath: packs\ATSAMD11D14AM_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD11D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7ACDFC92FD15ECFBF7D14D1E2E6A4A9F
- generatedChecksum: 87035D53A3764E99348B89DDBF84AD9D
  logicalPath: config\sam_d11_xpro
  name: ATSAMD11D14AM.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 87035D53A3764E99348B89DDBF84AD9D
format_version: v1.0
libraries:
- name: qtm_acq_samd11_0x0009.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_touch_key_cm0p_0x0002.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_freq_hop_auto_cm0p_0x0004.X.a
  path: /touch/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d11_xpro;../src/packs/ATSAMD11D14AM_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d11_xpro;../src/packs/ATSAMD11D14AM_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
