package:
  format-version: "1.0.0"
  name: "touch_apps"
  version: "v3.7.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "touch"
      type: "package"
      version: "v3.17.0"
