package:
  format-version: "1.0.0"
  name: "touch_apps"
  version: "3.4.0"
  type: "application"
  status: "production"
  
  dependencies:
    - name: "csp"
      type: "package"
      version: "3.14.0"
    - name: "touch"
      type: "package"
      version: "3.13.0"
