files:
- generatedChecksum: 46603BAEE159F18E57B4F158B6F09E7B
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: datastreamer_UART_sam.c
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 46603BAEE159F18E57B4F158B6F09E7B
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_d20_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: B455DD3F48E1FD7641D72CE54403B918
  logicalPath: config\sam_d20_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B455DD3F48E1FD7641D72CE54403B918
- generatedChecksum: DC686AE5D279FA6A3216D2011E5240F3
  logicalPath: config\sam_d20_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DC686AE5D279FA6A3216D2011E5240F3
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_d20_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5BB1A62F63E1D4CAB7A52139ED4B81E6
  logicalPath: config\sam_d20_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BB1A62F63E1D4CAB7A52139ED4B81E6
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_d20_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: C01556A578C620EE96855774B53E7468
  logicalPath: config\sam_d20_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C01556A578C620EE96855774B53E7468
- generatedChecksum: 4924A39380F3BDF3EE769570743C460D
  logicalPath: config\sam_d20_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4924A39380F3BDF3EE769570743C460D
- generatedChecksum: 8835A599D790DA05EF02E0F58944935F
  logicalPath: config\sam_d20_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8835A599D790DA05EF02E0F58944935F
- generatedChecksum: 9EC1182767AFF702BE209DC487D07162
  logicalPath: config\sam_d20_xpro\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9EC1182767AFF702BE209DC487D07162
- generatedChecksum: F5CFA8FECFDC204DE91036DE54CB2EEB
  logicalPath: config\sam_d20_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: F5CFA8FECFDC204DE91036DE54CB2EEB
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_d20_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: E26F28F74268BFF6BB476C224BA20A62
  logicalPath: config\sam_d20_xpro\touch
  name: touch.c
  physicalPath: touch
  security: NON_SECURE
  type: SOURCE
  userChecksum: E26F28F74268BFF6BB476C224BA20A62
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\sam_d20_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 39A5D2C5D0AB4E2EC3C11A2906DA07C0
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.db
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 39A5D2C5D0AB4E2EC3C11A2906DA07C0
- generatedChecksum: 9FF2C2973AD0F18E2A5DB6AA2F1685FF
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.ds
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9FF2C2973AD0F18E2A5DB6AA2F1685FF
- generatedChecksum: 30F21CB85FAC696CFAE2E5F1C16A1BF3
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.sc
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 30F21CB85FAC696CFAE2E5F1C16A1BF3
- generatedChecksum: 61614A3B65482ED7F8C8A87E871DAE3A
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 61614A3B65482ED7F8C8A87E871DAE3A
- generatedChecksum: DBC71687C01AED1E449ED8B829D68D75
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DBC71687C01AED1E449ED8B829D68D75
- generatedChecksum: 7B4B4106EDCDDAB2C07167B44A11708D
  logicalPath: packs\ATSAMD20J18_DFP
  name: atsamd20j18.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B4B4106EDCDDAB2C07167B44A11708D
- generatedChecksum: EF7C3C5918A153FC7CB8C785309F1F42
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EF7C3C5918A153FC7CB8C785309F1F42
- generatedChecksum: 9370572AD402AB9E975F0FDC2266795F
  logicalPath: config\sam_d20_xpro\touch\datastreamer
  name: datastreamer.h
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9370572AD402AB9E975F0FDC2266795F
- generatedChecksum: 1E95897BEB609CBE498A0D06CA7AA631
  logicalPath: config\sam_d20_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E95897BEB609CBE498A0D06CA7AA631
- generatedChecksum: 92912B70806DCA78FC309C856AD2F2E3
  logicalPath: config\sam_d20_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 92912B70806DCA78FC309C856AD2F2E3
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d20_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: F7E9546F7C4EFD53476AA132B069BC26
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F7E9546F7C4EFD53476AA132B069BC26
- generatedChecksum: 23236B108D96C78FC087DE9F46329431
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 23236B108D96C78FC087DE9F46329431
- generatedChecksum: 27F1A8D568DC6E31B9FC9F133335B831
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 27F1A8D568DC6E31B9FC9F133335B831
- generatedChecksum: C9C0FCAB478A35649A2BA7BDBD3CBA30
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C9C0FCAB478A35649A2BA7BDBD3CBA30
- generatedChecksum: 67F97FC39C2B50A1D0FC7E8E6CF00C6D
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 67F97FC39C2B50A1D0FC7E8E6CF00C6D
- generatedChecksum: A1DEB7F98ED9B61451CE5969BB69C4E2
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A1DEB7F98ED9B61451CE5969BB69C4E2
- generatedChecksum: C591D09F115E12D00921D14939E3900D
  logicalPath: config\sam_d20_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: C591D09F115E12D00921D14939E3900D
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d20_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_d20_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: 71D16914F1E580B0AF77141622DCD865
  logicalPath: config\sam_d20_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 71D16914F1E580B0AF77141622DCD865
- generatedChecksum: A400FB1AFF91C47B0909328AE363B1F5
  logicalPath: config\sam_d20_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: A400FB1AFF91C47B0909328AE363B1F5
- generatedChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
  logicalPath: config\sam_d20_xpro\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
- generatedChecksum: DCC0369AFDD597FB63203FB1B7488E8B
  logicalPath: config\sam_d20_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: DCC0369AFDD597FB63203FB1B7488E8B
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_d20_xpro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: 04C8E3C2A27856229F9387BED9467911
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 04C8E3C2A27856229F9387BED9467911
- generatedChecksum: AB9C19CB3D1C202CE9ED1C4D2A8B3DB6
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AB9C19CB3D1C202CE9ED1C4D2A8B3DB6
- generatedChecksum: 8F5153CF14498A1492E057678BE86F0F
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F5153CF14498A1492E057678BE86F0F
- generatedChecksum: 55FAD416646C70456CC8F553E19EEA94
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_acq_samd20_0x000e_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 55FAD416646C70456CC8F553E19EEA94
- generatedChecksum: 7DEFA02F559ACE61891DB528BF24E326
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_common_components_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DEFA02F559ACE61891DB528BF24E326
- generatedChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_freq_hop_auto_0x0004_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
- generatedChecksum: FB86752FE87F6FFC05CA323960F53142
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_scroller_0x000b_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: FB86752FE87F6FFC05CA323960F53142
- generatedChecksum: B40B26CBF970F40A2CB63C74002B65D4
  logicalPath: config\sam_d20_xpro\touch
  name: qtm_touch_key_0x0002_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: B40B26CBF970F40A2CB63C74002B65D4
- generatedChecksum: 7E3018CE00C07DD04076D474C2C8E201
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7E3018CE00C07DD04076D474C2C8E201
- generatedChecksum: 895AAF57F8BB10F1CF05A197AF51D20E
  logicalPath: packs\ATSAMD20J18_DFP\pio
  name: samd20j18.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 895AAF57F8BB10F1CF05A197AF51D20E
- generatedChecksum: BF83964046BC16326781DC33DB004B7B
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BF83964046BC16326781DC33DB004B7B
- generatedChecksum: 8F8BAA01E847D7C106FDDF03F0735423
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8F8BAA01E847D7C106FDDF03F0735423
- generatedChecksum: 69A268C7263485C322910EEFA8D97B5E
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 69A268C7263485C322910EEFA8D97B5E
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d20_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 90C9B1861C7C823EC92C70DD39DC81C4
  logicalPath: config\sam_d20_xpro\touch
  name: touch.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 90C9B1861C7C823EC92C70DD39DC81C4
- generatedChecksum: 6D4F4B6BDDCFAAB2A42B4CC277DF3E91
  logicalPath: config\sam_d20_xpro\touch
  name: touch_api_ptc.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 6D4F4B6BDDCFAAB2A42B4CC277DF3E91
- generatedChecksum: A102ED238794D81B3B354DBD9D8978FD
  logicalPath: packs\ATSAMD20J18_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD20J18_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A102ED238794D81B3B354DBD9D8978FD
- generatedChecksum: A24C9818BE52278D08A208C324917009
  logicalPath: config\sam_d20_xpro
  name: ATSAMD20J18.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: A24C9818BE52278D08A208C324917009
format_version: v1.0
libraries:
- name: qtm_acq_samd20_0x000e.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_touch_key_cm0p_0x0002.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_scroller_cm0p_0x000b.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_freq_hop_auto_cm0p_0x0004.X.a
  path: /touch/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d20_xpro;../src/packs/ATSAMD20J18_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d20_xpro;../src/packs/ATSAMD20J18_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
