files:
- generatedChecksum: 8031232838D3E2F489ABE24E4DAAACC2
  logicalPath: config\sam_d21_xpro\touch\datastreamer
  name: datastreamer_UART_sam.c
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8031232838D3E2F489ABE24E4DAAACC2
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_d21_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: BB1971162E622DE476E0E35B666BC68F
  logicalPath: config\sam_d21_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BB1971162E622DE476E0E35B666BC68F
- generatedChecksum: 8C42E7B4ABDB588B8A0534E5D2DF49DB
  logicalPath: config\sam_d21_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8C42E7B4ABDB588B8A0534E5D2DF49DB
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_d21_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: C457301855A9CEF0BF80514025BA9961
  logicalPath: config\sam_d21_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: C457301855A9CEF0BF80514025BA9961
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_d21_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: C01556A578C620EE96855774B53E7468
  logicalPath: config\sam_d21_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C01556A578C620EE96855774B53E7468
- generatedChecksum: 4924A39380F3BDF3EE769570743C460D
  logicalPath: config\sam_d21_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4924A39380F3BDF3EE769570743C460D
- generatedChecksum: 907585A9C42144CECAE3D8AE4535D954
  logicalPath: config\sam_d21_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 907585A9C42144CECAE3D8AE4535D954
- generatedChecksum: 9EC1182767AFF702BE209DC487D07162
  logicalPath: config\sam_d21_xpro\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9EC1182767AFF702BE209DC487D07162
- generatedChecksum: 657CDDE80BEBAD774BEAA083344C4312
  logicalPath: config\sam_d21_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 657CDDE80BEBAD774BEAA083344C4312
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_d21_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: B4A8E1E751B9B14897AB997FFAF7C969
  logicalPath: config\sam_d21_xpro\touch
  name: touch.c
  physicalPath: touch
  security: NON_SECURE
  type: SOURCE
  userChecksum: B4A8E1E751B9B14897AB997FFAF7C969
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\sam_d21_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: C90096E1F900F7C19A1751188E3A8E32
  logicalPath: config\sam_d21_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.db
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: C90096E1F900F7C19A1751188E3A8E32
- generatedChecksum: 696D18869D552C0F6F8591673EEF593C
  logicalPath: config\sam_d21_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.ds
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 696D18869D552C0F6F8591673EEF593C
- generatedChecksum: DD2922E89ECE8DB338D63C81A090A09E
  logicalPath: config\sam_d21_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.sc
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: DD2922E89ECE8DB338D63C81A090A09E
- generatedChecksum: E83A2568EB70A3E393A9421C4CEDDDD5
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E83A2568EB70A3E393A9421C4CEDDDD5
- generatedChecksum: 590A4F4CE794B1EB4CDE657634C91913
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 590A4F4CE794B1EB4CDE657634C91913
- generatedChecksum: D03E3BB47A437765D48AB851735F684D
  logicalPath: packs\ATSAMD21J18A_DFP
  name: atsamd21j18a.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: D03E3BB47A437765D48AB851735F684D
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: 016B5B4A71E106E734B16CA1517FF382
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 016B5B4A71E106E734B16CA1517FF382
- generatedChecksum: 9370572AD402AB9E975F0FDC2266795F
  logicalPath: config\sam_d21_xpro\touch\datastreamer
  name: datastreamer.h
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9370572AD402AB9E975F0FDC2266795F
- generatedChecksum: 1E95897BEB609CBE498A0D06CA7AA631
  logicalPath: config\sam_d21_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E95897BEB609CBE498A0D06CA7AA631
- generatedChecksum: A62880149571045CACABCBB3AC375EAD
  logicalPath: config\sam_d21_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A62880149571045CACABCBB3AC375EAD
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d21_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: C2E075A57123D0F17F6743EB79FB5708
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C2E075A57123D0F17F6743EB79FB5708
- generatedChecksum: 817445C5CD46BF44AEA791F24FFCFD9B
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 817445C5CD46BF44AEA791F24FFCFD9B
- generatedChecksum: D354D94F76074F550A3D39339988740E
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D354D94F76074F550A3D39339988740E
- generatedChecksum: CCEBBAD0032227AD71BE82D0A235ADD8
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CCEBBAD0032227AD71BE82D0A235ADD8
- generatedChecksum: 1F81BE55AB45CB807013941A75AA1A57
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1F81BE55AB45CB807013941A75AA1A57
- generatedChecksum: 56D435F7656CC2343B84F1E66D164D64
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 56D435F7656CC2343B84F1E66D164D64
- generatedChecksum: 998DBA248933E5682F2276B60B8FD8D8
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: i2s.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 998DBA248933E5682F2276B60B8FD8D8
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: F37178E00FC83646B507901642A0100D
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F37178E00FC83646B507901642A0100D
- generatedChecksum: 7296DA017FF9C40DCC08191D6999B77B
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7296DA017FF9C40DCC08191D6999B77B
- generatedChecksum: D5A9C90744DEFF4CCDD467B77B6406CB
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D5A9C90744DEFF4CCDD467B77B6406CB
- generatedChecksum: C591D09F115E12D00921D14939E3900D
  logicalPath: config\sam_d21_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: C591D09F115E12D00921D14939E3900D
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d21_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_d21_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: 71D16914F1E580B0AF77141622DCD865
  logicalPath: config\sam_d21_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 71D16914F1E580B0AF77141622DCD865
- generatedChecksum: 4BB926A2858D02FA6D9593058C7B4939
  logicalPath: config\sam_d21_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 4BB926A2858D02FA6D9593058C7B4939
- generatedChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
  logicalPath: config\sam_d21_xpro\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
- generatedChecksum: DCC0369AFDD597FB63203FB1B7488E8B
  logicalPath: config\sam_d21_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: DCC0369AFDD597FB63203FB1B7488E8B
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_d21_xpro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: EBC9AD17B5DCF76A8EDA531E3D2ECDA5
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EBC9AD17B5DCF76A8EDA531E3D2ECDA5
- generatedChecksum: 7AED24682E6782ACD411A220C99C4F7A
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7AED24682E6782ACD411A220C99C4F7A
- generatedChecksum: B838D9B01315613C8EFF25C5BB950F80
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B838D9B01315613C8EFF25C5BB950F80
- generatedChecksum: 4E87A950B5EACCDBF4DF612FCECA995B
  logicalPath: config\sam_d21_xpro\touch
  name: qtm_acq_samd21_0x0024_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 4E87A950B5EACCDBF4DF612FCECA995B
- generatedChecksum: 7DEFA02F559ACE61891DB528BF24E326
  logicalPath: config\sam_d21_xpro\touch
  name: qtm_common_components_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DEFA02F559ACE61891DB528BF24E326
- generatedChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
  logicalPath: config\sam_d21_xpro\touch
  name: qtm_freq_hop_auto_0x0004_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
- generatedChecksum: FB86752FE87F6FFC05CA323960F53142
  logicalPath: config\sam_d21_xpro\touch
  name: qtm_scroller_0x000b_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: FB86752FE87F6FFC05CA323960F53142
- generatedChecksum: B40B26CBF970F40A2CB63C74002B65D4
  logicalPath: config\sam_d21_xpro\touch
  name: qtm_touch_key_0x0002_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: B40B26CBF970F40A2CB63C74002B65D4
- generatedChecksum: 87D1C55E9ECF3BCCB24FA600CBFCC930
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 87D1C55E9ECF3BCCB24FA600CBFCC930
- generatedChecksum: C5D1633B6BB74A69DB0CBA77291BC43C
  logicalPath: packs\ATSAMD21J18A_DFP\pio
  name: samd21j18a.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: C5D1633B6BB74A69DB0CBA77291BC43C
- generatedChecksum: 4253FCE0B35C0AB2AA0253652C488761
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4253FCE0B35C0AB2AA0253652C488761
- generatedChecksum: 0258BE6535CDDE44682CC0CDCB222880
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0258BE6535CDDE44682CC0CDCB222880
- generatedChecksum: E9BCB2B0F7AA6142C2681C1155F88131
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E9BCB2B0F7AA6142C2681C1155F88131
- generatedChecksum: 5819925250D9C7C86B56A48BF0949196
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5819925250D9C7C86B56A48BF0949196
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d21_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 15F95D5FD44EAC28B3319D8407BB7990
  logicalPath: config\sam_d21_xpro\touch
  name: touch.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 15F95D5FD44EAC28B3319D8407BB7990
- generatedChecksum: 2FC2628A1C948CEBF651C1960A017673
  logicalPath: config\sam_d21_xpro\touch
  name: touch_api_ptc.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 2FC2628A1C948CEBF651C1960A017673
- generatedChecksum: F123D6104DB9C55CD684CE27F3B22781
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F123D6104DB9C55CD684CE27F3B22781
- generatedChecksum: AF14D78B734053187B6E93E19BD70449
  logicalPath: packs\ATSAMD21J18A_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD21J18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AF14D78B734053187B6E93E19BD70449
- generatedChecksum: D5CD9172C8EF08FDC00E4F569329FFCF
  logicalPath: config\sam_d21_xpro
  name: ATSAMD21J18A.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: D5CD9172C8EF08FDC00E4F569329FFCF
format_version: v1.0
libraries:
- name: qtm_acq_samd21_0x0024.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_touch_key_cm0p_0x0002.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_scroller_cm0p_0x000b.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_freq_hop_auto_cm0p_0x0004.X.a
  path: /touch/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d21_xpro;../src/packs/ATSAMD21J18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d21_xpro;../src/packs/ATSAMD21J18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
