format_version: v1.0
configName: sam_l10_xpro
folderName: sam_l10_xpro
frameworkPath: C:\Users\I70181\Harmony3
processor: ATSAML10E16A
projectName: sam_l10_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAML10_DFP\3.9.116\atdf\ATSAML10E16A.atdf
