configName: sam_l10_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAML10E16A
projectName: ''
settings:
  PackageFilter: bsp;core;csp;quick_docs;touch;touch_apps;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML10_DFP\3.6.95\atdf\ATSAML10E16A.atdf
