configName: sam_da1_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMDA1J16B
projectName: ''
settings:
  PackageFilter: bsp;core;core_apps_pic32cm_mc00;csp;csp_apps_pic32cm_mc00;dev_packs;quick_docs;touch;touch_apps
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMDA1_DFP\2.5.68\atdf\ATSAMDA1J16B.atdf
