files:
- generatedChecksum: FBA52D1D3B3584ACBC723FBBDFE8D2C4
  logicalPath: config\sam_d10_xmini\touch\datastreamer
  name: datastreamer_UART_sam.c
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: SOURCE
  userChecksum: FBA52D1D3B3584ACBC723FBBDFE8D2C4
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_d10_xmini
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: 5647482ADBDFBD1A8AD79F164A9D63B7
  logicalPath: config\sam_d10_xmini
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5647482ADBDFBD1A8AD79F164A9D63B7
- generatedChecksum: D322F78010C3D82C669A586D6D064962
  logicalPath: config\sam_d10_xmini
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D322F78010C3D82C669A586D6D064962
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_d10_xmini
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: AE72521AB3C01C5B02FACDED0D1788AD
  logicalPath: config\sam_d10_xmini\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: AE72521AB3C01C5B02FACDED0D1788AD
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_d10_xmini\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: C01556A578C620EE96855774B53E7468
  logicalPath: config\sam_d10_xmini\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C01556A578C620EE96855774B53E7468
- generatedChecksum: 4924A39380F3BDF3EE769570743C460D
  logicalPath: config\sam_d10_xmini\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4924A39380F3BDF3EE769570743C460D
- generatedChecksum: 284294059E48BDC21B79EDCC6ED873E0
  logicalPath: config\sam_d10_xmini\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 284294059E48BDC21B79EDCC6ED873E0
- generatedChecksum: 9EC1182767AFF702BE209DC487D07162
  logicalPath: config\sam_d10_xmini\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9EC1182767AFF702BE209DC487D07162
- generatedChecksum: AE3FAE408966D36AF31DA383896E3B67
  logicalPath: config\sam_d10_xmini\peripheral\sercom\usart
  name: plib_sercom0_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: AE3FAE408966D36AF31DA383896E3B67
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_d10_xmini
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: 703272BCEC83304E266B8C6ADCF4900D
  logicalPath: config\sam_d10_xmini\touch
  name: touch.c
  physicalPath: touch
  security: NON_SECURE
  type: SOURCE
  userChecksum: 703272BCEC83304E266B8C6ADCF4900D
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\sam_d10_xmini\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: DAA7E72FD50A6A3448B9D3B72CDB2105
  logicalPath: config\sam_d10_xmini\touch\datastreamer
  name: 03EB00000000000000AA5501.db
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: DAA7E72FD50A6A3448B9D3B72CDB2105
- generatedChecksum: 302C94482B5355A1AB4E2E0E34D28CB9
  logicalPath: config\sam_d10_xmini\touch\datastreamer
  name: 03EB00000000000000AA5501.ds
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 302C94482B5355A1AB4E2E0E34D28CB9
- generatedChecksum: 564DFA4C66EFD42BF3DC98FD0C9ACB9B
  logicalPath: config\sam_d10_xmini\touch\datastreamer
  name: 03EB00000000000000AA5501.sc
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 564DFA4C66EFD42BF3DC98FD0C9ACB9B
- generatedChecksum: C343CD58839AC5E505982EFFBC751E14
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C343CD58839AC5E505982EFFBC751E14
- generatedChecksum: 188EA3093489E7794B87AEC720B74BC0
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 188EA3093489E7794B87AEC720B74BC0
- generatedChecksum: 012033C6691CEC45C78CB4F7C59C0D17
  logicalPath: packs\ATSAMD10D14AM_DFP
  name: atsamd10d14am.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 012033C6691CEC45C78CB4F7C59C0D17
- generatedChecksum: 4BA8D35393F06D23A4A5E7DB43985E2D
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4BA8D35393F06D23A4A5E7DB43985E2D
- generatedChecksum: 9370572AD402AB9E975F0FDC2266795F
  logicalPath: config\sam_d10_xmini\touch\datastreamer
  name: datastreamer.h
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9370572AD402AB9E975F0FDC2266795F
- generatedChecksum: B2B4041A724E2C7DC1D6AB08F263D147
  logicalPath: config\sam_d10_xmini
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B2B4041A724E2C7DC1D6AB08F263D147
- generatedChecksum: CCE01A3EDE161444A0F327599BEE3A6C
  logicalPath: config\sam_d10_xmini
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CCE01A3EDE161444A0F327599BEE3A6C
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_d10_xmini
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: 34FF3401373EBD88CC1D2624DAA4CD3E
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 34FF3401373EBD88CC1D2624DAA4CD3E
- generatedChecksum: 9D9D3E9D998B7CFA68288603455B1F37
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D9D3E9D998B7CFA68288603455B1F37
- generatedChecksum: C338CACE4D8345CADA50B82EA054464C
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C338CACE4D8345CADA50B82EA054464C
- generatedChecksum: 84EF90AE98A2FBC8CBDBC50AE9F45ABF
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 84EF90AE98A2FBC8CBDBC50AE9F45ABF
- generatedChecksum: DC159880CCC82C5A66A880B0835E8163
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DC159880CCC82C5A66A880B0835E8163
- generatedChecksum: 89BC67FFDA77283C52B20BD767745D96
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 89BC67FFDA77283C52B20BD767745D96
- generatedChecksum: 878E2ADAC1DFEE56C1E5805415C2B3A5
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 878E2ADAC1DFEE56C1E5805415C2B3A5
- generatedChecksum: DAC6219507C2A136A9443831BA4E5008
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DAC6219507C2A136A9443831BA4E5008
- generatedChecksum: 1D6CC7DC71E44DF7754941D3FDD39C07
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D6CC7DC71E44DF7754941D3FDD39C07
- generatedChecksum: 729DB333FDDAD65AB9172F82E0E143D3
  logicalPath: config\sam_d10_xmini\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: 729DB333FDDAD65AB9172F82E0E143D3
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_d10_xmini\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_d10_xmini\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: D39664ECFA43A34431A127602F3A82ED
  logicalPath: config\sam_d10_xmini\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: D39664ECFA43A34431A127602F3A82ED
- generatedChecksum: 47ADE2666567461A43270326066DB95C
  logicalPath: config\sam_d10_xmini\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 47ADE2666567461A43270326066DB95C
- generatedChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
  logicalPath: config\sam_d10_xmini\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 555E6DA59F0EC034C1C4776C8FBC9C7F
- generatedChecksum: 9E847139EB4A35248CEAA3CF830D18DD
  logicalPath: config\sam_d10_xmini\peripheral\sercom\usart
  name: plib_sercom0_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E847139EB4A35248CEAA3CF830D18DD
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_d10_xmini\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: 4C43D4E209CD38DB5EDD138FFBF2E7D9
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C43D4E209CD38DB5EDD138FFBF2E7D9
- generatedChecksum: DBE67E6FE2EA9DA238E2D88FE2F2F9F7
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DBE67E6FE2EA9DA238E2D88FE2F2F9F7
- generatedChecksum: DBB6073CCE646F622660737A08A905FB
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: DBB6073CCE646F622660737A08A905FB
- generatedChecksum: 50442CD77906A8E47B90ED5749D5AEB7
  logicalPath: config\sam_d10_xmini\touch
  name: qtm_acq_samd1x_0x0009_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 50442CD77906A8E47B90ED5749D5AEB7
- generatedChecksum: 7DEFA02F559ACE61891DB528BF24E326
  logicalPath: config\sam_d10_xmini\touch
  name: qtm_common_components_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DEFA02F559ACE61891DB528BF24E326
- generatedChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
  logicalPath: config\sam_d10_xmini\touch
  name: qtm_freq_hop_auto_0x0004_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
- generatedChecksum: B40B26CBF970F40A2CB63C74002B65D4
  logicalPath: config\sam_d10_xmini\touch
  name: qtm_touch_key_0x0002_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: B40B26CBF970F40A2CB63C74002B65D4
- generatedChecksum: 5CCEBFB2063928ADA1F031B6C871437A
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5CCEBFB2063928ADA1F031B6C871437A
- generatedChecksum: 5B40ABA3D9E9D16AB560AE1B74F9CA1B
  logicalPath: packs\ATSAMD10D14AM_DFP\pio
  name: samd10d14am.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 5B40ABA3D9E9D16AB560AE1B74F9CA1B
- generatedChecksum: FCF51B27133192191EC8D906DC44C02D
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FCF51B27133192191EC8D906DC44C02D
- generatedChecksum: 37FA8BA5DECCDFBE49C91DE9E02DF5A4
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 37FA8BA5DECCDFBE49C91DE9E02DF5A4
- generatedChecksum: 974AA0B9054496A72C0F31F38F99F753
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 974AA0B9054496A72C0F31F38F99F753
- generatedChecksum: 090BA7A8E8F63B0424567270D7528F2E
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 090BA7A8E8F63B0424567270D7528F2E
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_d10_xmini
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 9DECCE8355E671A5C9E79BEABA2E990B
  logicalPath: config\sam_d10_xmini\touch
  name: touch.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DECCE8355E671A5C9E79BEABA2E990B
- generatedChecksum: 71EEB5B41E5AEE48364C704BD816A315
  logicalPath: config\sam_d10_xmini\touch
  name: touch_api_ptc.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 71EEB5B41E5AEE48364C704BD816A315
- generatedChecksum: B1E85E22BAE85D76EF38416FC2048D75
  logicalPath: packs\ATSAMD10D14AM_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMD10D14AM_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B1E85E22BAE85D76EF38416FC2048D75
- generatedChecksum: 7F53230AEA0F407A33B2D14BA1C5940F
  logicalPath: config\sam_d10_xmini
  name: ATSAMD10D14AM.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 7F53230AEA0F407A33B2D14BA1C5940F
format_version: v1.0
libraries:
- name: qtm_acq_samd10_0x0009.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_touch_key_cm0p_0x0002.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_freq_hop_auto_cm0p_0x0004.X.a
  path: /touch/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d10_xmini;../src/packs/ATSAMD10D14AM_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_d10_xmini;../src/packs/ATSAMD10D14AM_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
