configName: sam_l10_xpro
folderName: sam_l10_xpro
format_version: v1.0
frameworkPath: D:\Harmony\h3_repo
processor: ATSAML10E16A
projectName: sam_l10_xpro
settings:
  PackageFilter: bsp;core;core_apps_pic32cm_mc00;csp;csp_apps_pic32cm_mc00;dev_packs;quick_docs;touch;touch_apps
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML10_DFP\3.8.105\atdf\ATSAML10E16A.atdf
