configName: pic32cm_LS00_cpro
folderName: pic32cm_LS00_cpro_NonSecure
format_version: v1.0
frameworkPath: D:\Harmony\h3_repo
processor: PIC32CM5164LS00100
projectName: _NonSecure
settings:
  PackageFilter: bsp;core;core_apps_pic32cm_mc00;csp;csp_apps_pic32cm_mc00;dev_packs;quick_docs;touch;touch_apps
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CM-LS_DFP\1.0.110\PIC32CM-LS00\atdf\PIC32CM5164LS00100.atdf
