format_version: v1.0
type: UniqueComponent
attributes: {id: nvmctrl}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: MEMORY_MEDIA_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Integer
    attributes: {id: NVM_RWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvmctrl, value: '1'}
  - type: String
    attributes: {id: START_ADDRESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20000'}
- type: ElementPosition
  attributes: {x: '9', y: '20', id: nvmctrl}
