files:
- generatedChecksum: 46603BAEE159F18E57B4F158B6F09E7B
  logicalPath: config\sam_l21_xpro\touch\datastreamer
  name: datastreamer_UART_sam.c
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 46603BAEE159F18E57B4F158B6F09E7B
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_l21_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: 6A582D90C494CF97D976AEF28AB14ECF
  logicalPath: config\sam_l21_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6A582D90C494CF97D976AEF28AB14ECF
- generatedChecksum: 17D3FA9C57493F34B2EFA7360716589C
  logicalPath: config\sam_l21_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 17D3FA9C57493F34B2EFA7360716589C
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_l21_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8D17F2D74B6A481203FECC47880CC0F6
  logicalPath: config\sam_l21_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8D17F2D74B6A481203FECC47880CC0F6
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_l21_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: C01556A578C620EE96855774B53E7468
  logicalPath: config\sam_l21_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C01556A578C620EE96855774B53E7468
- generatedChecksum: D005B7382C356EE67399EB3FC381125F
  logicalPath: config\sam_l21_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: D005B7382C356EE67399EB3FC381125F
- generatedChecksum: 86046DCDD50479F5218553279E51C61C
  logicalPath: config\sam_l21_xpro\peripheral\pm
  name: plib_pm.c
  physicalPath: peripheral\pm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 86046DCDD50479F5218553279E51C61C
- generatedChecksum: 914CCB18C2EA31B8A268DF08603A3F27
  logicalPath: config\sam_l21_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 914CCB18C2EA31B8A268DF08603A3F27
- generatedChecksum: 1FD597E44EC6AAFC7695AD48CE532CBE
  logicalPath: config\sam_l21_xpro\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1FD597E44EC6AAFC7695AD48CE532CBE
- generatedChecksum: E60C30692340FEB13B459473AC07667A
  logicalPath: config\sam_l21_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: E60C30692340FEB13B459473AC07667A
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_l21_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: 6A8AA8EC6EA93CB6753B7004F06E8497
  logicalPath: config\sam_l21_xpro\touch
  name: touch.c
  physicalPath: touch
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6A8AA8EC6EA93CB6753B7004F06E8497
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\sam_l21_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: 39A5D2C5D0AB4E2EC3C11A2906DA07C0
  logicalPath: config\sam_l21_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.db
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 39A5D2C5D0AB4E2EC3C11A2906DA07C0
- generatedChecksum: 9FF2C2973AD0F18E2A5DB6AA2F1685FF
  logicalPath: config\sam_l21_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.ds
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9FF2C2973AD0F18E2A5DB6AA2F1685FF
- generatedChecksum: 30F21CB85FAC696CFAE2E5F1C16A1BF3
  logicalPath: config\sam_l21_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.sc
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 30F21CB85FAC696CFAE2E5F1C16A1BF3
- generatedChecksum: 7B153601706A77DB35A9C72C3FE310BC
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7B153601706A77DB35A9C72C3FE310BC
- generatedChecksum: 9F249DCC13E6810A16D8D34BF7A69F13
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F249DCC13E6810A16D8D34BF7A69F13
- generatedChecksum: 907AB16D59A756D6E57BFFBEC25D508A
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: aes.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 907AB16D59A756D6E57BFFBEC25D508A
- generatedChecksum: DF56BA97D74944C0C34AA5749FC7D7E4
  logicalPath: packs\ATSAML21J18B_DFP
  name: atsaml21j18b.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: DF56BA97D74944C0C34AA5749FC7D7E4
- generatedChecksum: 1EF033C940C92F1E31F36FB21DFA3C05
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: ccl.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1EF033C940C92F1E31F36FB21DFA3C05
- generatedChecksum: 375754192B0550C66E7AD8341680C097
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 375754192B0550C66E7AD8341680C097
- generatedChecksum: 9370572AD402AB9E975F0FDC2266795F
  logicalPath: config\sam_l21_xpro\touch\datastreamer
  name: datastreamer.h
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9370572AD402AB9E975F0FDC2266795F
- generatedChecksum: 026B2FEFB3277A71F76F22956C001790
  logicalPath: config\sam_l21_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 026B2FEFB3277A71F76F22956C001790
- generatedChecksum: 2A807DC54F546A4D03D1E8ACC3B764BB
  logicalPath: config\sam_l21_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2A807DC54F546A4D03D1E8ACC3B764BB
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_l21_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: 837584806FFB55DDD53E51097668FB95
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 837584806FFB55DDD53E51097668FB95
- generatedChecksum: 9233CAADC734E50E033038439BF4FC98
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9233CAADC734E50E033038439BF4FC98
- generatedChecksum: B22C804C1ED3DBD5AD0EC0F4EC722675
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B22C804C1ED3DBD5AD0EC0F4EC722675
- generatedChecksum: 53FDC007CB14A6FB69EB336878F7456B
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 53FDC007CB14A6FB69EB336878F7456B
- generatedChecksum: 08EDC8E5654D6ED745DD266ED62ABE24
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 08EDC8E5654D6ED745DD266ED62ABE24
- generatedChecksum: 4F071074DF4CDE3A60FB6FB72EE43AFA
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: mclk.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4F071074DF4CDE3A60FB6FB72EE43AFA
- generatedChecksum: BF3F18AB7046CD6AEE31291B49F94D26
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BF3F18AB7046CD6AEE31291B49F94D26
- generatedChecksum: 676D82AC6F6947C55DFF126A3454E3D9
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 676D82AC6F6947C55DFF126A3454E3D9
- generatedChecksum: 3E669EE6D654259728300E45FB6C905F
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: opamp.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 3E669EE6D654259728300E45FB6C905F
- generatedChecksum: 161310BCDE493E15C39B8B4FFFAB6B99
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: osc32kctrl.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 161310BCDE493E15C39B8B4FFFAB6B99
- generatedChecksum: 23BA08BEBBB6C0111C3CFAD0AC0B6E6A
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: oscctrl.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 23BA08BEBBB6C0111C3CFAD0AC0B6E6A
- generatedChecksum: 27EEEC90C69D06171061E911DB316C2B
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 27EEEC90C69D06171061E911DB316C2B
- generatedChecksum: 78387EA60F98EE9F5602C2EB8CFEA8B3
  logicalPath: config\sam_l21_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: 78387EA60F98EE9F5602C2EB8CFEA8B3
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_l21_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_l21_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: E94C2F2827F3CB08C565ADF200C747B6
  logicalPath: config\sam_l21_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: E94C2F2827F3CB08C565ADF200C747B6
- generatedChecksum: 2C6F9BA1BFA523200ED784A7D4FC3C81
  logicalPath: config\sam_l21_xpro\peripheral\pm
  name: plib_pm.h
  physicalPath: peripheral\pm
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C6F9BA1BFA523200ED784A7D4FC3C81
- generatedChecksum: C09AAE871C86C6CBD1E615560965EF62
  logicalPath: config\sam_l21_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: C09AAE871C86C6CBD1E615560965EF62
- generatedChecksum: ABD082323CACADDFD4FA4B1237ABDA82
  logicalPath: config\sam_l21_xpro\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: ABD082323CACADDFD4FA4B1237ABDA82
- generatedChecksum: DCC0369AFDD597FB63203FB1B7488E8B
  logicalPath: config\sam_l21_xpro\peripheral\sercom\usart
  name: plib_sercom3_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: DCC0369AFDD597FB63203FB1B7488E8B
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_l21_xpro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: ACF08DC4715BA97CE356D06A58D18141
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: ACF08DC4715BA97CE356D06A58D18141
- generatedChecksum: 9A89B9C15F26E0617EB15A08A64DCFDE
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9A89B9C15F26E0617EB15A08A64DCFDE
- generatedChecksum: EDDB5EBB9B53A16E065A2ED63494E521
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EDDB5EBB9B53A16E065A2ED63494E521
- generatedChecksum: 152501BF4273411188FA60C657EF93FE
  logicalPath: config\sam_l21_xpro\touch
  name: qtm_acq_saml21_0x0026_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 152501BF4273411188FA60C657EF93FE
- generatedChecksum: 7DEFA02F559ACE61891DB528BF24E326
  logicalPath: config\sam_l21_xpro\touch
  name: qtm_common_components_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DEFA02F559ACE61891DB528BF24E326
- generatedChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
  logicalPath: config\sam_l21_xpro\touch
  name: qtm_freq_hop_auto_0x0004_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
- generatedChecksum: FB86752FE87F6FFC05CA323960F53142
  logicalPath: config\sam_l21_xpro\touch
  name: qtm_scroller_0x000b_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: FB86752FE87F6FFC05CA323960F53142
- generatedChecksum: B40B26CBF970F40A2CB63C74002B65D4
  logicalPath: config\sam_l21_xpro\touch
  name: qtm_touch_key_0x0002_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: B40B26CBF970F40A2CB63C74002B65D4
- generatedChecksum: 7F8F4E5F1C90B69DA39621426748BB97
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F8F4E5F1C90B69DA39621426748BB97
- generatedChecksum: B64D3A47C6C3C3A06CE4E8A6C95EDB6B
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B64D3A47C6C3C3A06CE4E8A6C95EDB6B
- generatedChecksum: 20F8C32F03D09B144CE27EB09FAE4DA1
  logicalPath: packs\ATSAML21J18B_DFP\pio
  name: saml21j18b.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 20F8C32F03D09B144CE27EB09FAE4DA1
- generatedChecksum: FD9FFC5319F1847FC54CA0AB7ED5D7D4
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FD9FFC5319F1847FC54CA0AB7ED5D7D4
- generatedChecksum: 7EEB008817CF57D99A651D5311D3C104
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7EEB008817CF57D99A651D5311D3C104
- generatedChecksum: 74859C907DB8105D2BFC326EF036DF41
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 74859C907DB8105D2BFC326EF036DF41
- generatedChecksum: 90D2FCE7FAB635A193D9FBFB91A52EC4
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 90D2FCE7FAB635A193D9FBFB91A52EC4
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_l21_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 0290111BC8EB765BC650778F0074B3E9
  logicalPath: config\sam_l21_xpro\touch
  name: touch.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 0290111BC8EB765BC650778F0074B3E9
- generatedChecksum: 4D89783F9CAFB1686AEB5056E7549C23
  logicalPath: config\sam_l21_xpro\touch
  name: touch_api_ptc.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D89783F9CAFB1686AEB5056E7549C23
- generatedChecksum: 089AB9C09BC574AB9914F47DDF587886
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: trng.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 089AB9C09BC574AB9914F47DDF587886
- generatedChecksum: 35CC4F70DE84A5DF099FA4E3181DA70C
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 35CC4F70DE84A5DF099FA4E3181DA70C
- generatedChecksum: C14E9D53F26337F180FEEABABD5943DC
  logicalPath: packs\ATSAML21J18B_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAML21J18B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C14E9D53F26337F180FEEABABD5943DC
- generatedChecksum: 8A65BB6F296A8430DE1C6F6FE23E3538
  logicalPath: config\sam_l21_xpro
  name: ATSAML21J18B.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 8A65BB6F296A8430DE1C6F6FE23E3538
format_version: v1.0
libraries:
- name: qtm_saml21_acq_0x0026.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_touch_key_cm0p_0x0002.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_scroller_cm0p_0x000b.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_freq_hop_auto_cm0p_0x0004.X.a
  path: /touch/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_l21_xpro;../src/packs/ATSAML21J18B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_l21_xpro;../src/packs/ATSAML21J18B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
