files:
- generatedChecksum: B01D5D5949367B60911AD1E8B0DF26CE
  logicalPath: config\sam_l22_xpro\touch\datastreamer
  name: datastreamer_UART_sam.c
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: SOURCE
  userChecksum: B01D5D5949367B60911AD1E8B0DF26CE
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config\sam_l22_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: EF94934D5D948C9AC227A59AECED21FE
  logicalPath: config\sam_l22_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EF94934D5D948C9AC227A59AECED21FE
- generatedChecksum: E598F8A736DD65E0A81EF72E385741C0
  logicalPath: config\sam_l22_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E598F8A736DD65E0A81EF72E385741C0
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config\sam_l22_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: EF8073C09A0DC7286C8BB836B0D0F8AA
  logicalPath: config\sam_l22_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: EF8073C09A0DC7286C8BB836B0D0F8AA
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_l22_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: C01556A578C620EE96855774B53E7468
  logicalPath: config\sam_l22_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: C01556A578C620EE96855774B53E7468
- generatedChecksum: D005B7382C356EE67399EB3FC381125F
  logicalPath: config\sam_l22_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: D005B7382C356EE67399EB3FC381125F
- generatedChecksum: 42403DBB3C7A07907E04B74F85301F70
  logicalPath: config\sam_l22_xpro\peripheral\pm
  name: plib_pm.c
  physicalPath: peripheral\pm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42403DBB3C7A07907E04B74F85301F70
- generatedChecksum: C785E373C84193280B725E56A2346A12
  logicalPath: config\sam_l22_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: C785E373C84193280B725E56A2346A12
- generatedChecksum: 7B8935F0F689CEA0DF95CBB6C29C66A9
  logicalPath: config\sam_l22_xpro\peripheral\rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7B8935F0F689CEA0DF95CBB6C29C66A9
- generatedChecksum: F08E797D5B766466E5F25A8E5F26FE7D
  logicalPath: config\sam_l22_xpro\peripheral\sercom\usart
  name: plib_sercom0_usart.c
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: SOURCE
  userChecksum: F08E797D5B766466E5F25A8E5F26FE7D
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config\sam_l22_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: 50EB165095649C61773386A15793C41A
  logicalPath: config\sam_l22_xpro\touch
  name: touch.c
  physicalPath: touch
  security: NON_SECURE
  type: SOURCE
  userChecksum: 50EB165095649C61773386A15793C41A
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\sam_l22_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: E7E77254A550AF0835AD9293B0C39E0E
  logicalPath: config\sam_l22_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.db
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: E7E77254A550AF0835AD9293B0C39E0E
- generatedChecksum: 4E0C368059E34863CDFC5D86290A9B9F
  logicalPath: config\sam_l22_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.ds
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 4E0C368059E34863CDFC5D86290A9B9F
- generatedChecksum: 9F6E47B812DCFE006F44D42441789D25
  logicalPath: config\sam_l22_xpro\touch\datastreamer
  name: 03EB00000000000000AA5501.sc
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9F6E47B812DCFE006F44D42441789D25
- generatedChecksum: F1D73DF6086A6010477CDF8552DAEA15
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F1D73DF6086A6010477CDF8552DAEA15
- generatedChecksum: 6C054935990DD4B0F81F0A4C0EC57807
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6C054935990DD4B0F81F0A4C0EC57807
- generatedChecksum: E127B0D88860293911B6F6B3BD2E06CD
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: aes.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E127B0D88860293911B6F6B3BD2E06CD
- generatedChecksum: 2EEBFE4A190F1E3394E011F946A31213
  logicalPath: packs\ATSAML22N18A_DFP
  name: atsaml22n18a.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 2EEBFE4A190F1E3394E011F946A31213
- generatedChecksum: 52A702E5829ECBDE3074433E575E9055
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: ccl.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 52A702E5829ECBDE3074433E575E9055
- generatedChecksum: 9370572AD402AB9E975F0FDC2266795F
  logicalPath: config\sam_l22_xpro\touch\datastreamer
  name: datastreamer.h
  physicalPath: touch\datastreamer
  security: NON_SECURE
  type: HEADER
  userChecksum: 9370572AD402AB9E975F0FDC2266795F
- generatedChecksum: 9765148CFF0D1853517815755DD28E4D
  logicalPath: config\sam_l22_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9765148CFF0D1853517815755DD28E4D
- generatedChecksum: 04802C2E9A2452C8D29CEF9F1C0B7280
  logicalPath: config\sam_l22_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 04802C2E9A2452C8D29CEF9F1C0B7280
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_l22_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: D1B1C9A90B5E7A981E5AE8BD0DBD75C6
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D1B1C9A90B5E7A981E5AE8BD0DBD75C6
- generatedChecksum: 0DB1883F96D3766D1CCA0D60A54567A8
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0DB1883F96D3766D1CCA0D60A54567A8
- generatedChecksum: AD0798715431550F9B5DF562D0D6056E
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: AD0798715431550F9B5DF562D0D6056E
- generatedChecksum: 679A710731A0EB63D52C03C42EA27406
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 679A710731A0EB63D52C03C42EA27406
- generatedChecksum: A8B1C2CDECC764F8FF8BC5FE872DE8DD
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: freqm.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A8B1C2CDECC764F8FF8BC5FE872DE8DD
- generatedChecksum: 98487E012A67650ED13BC0A812140446
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 98487E012A67650ED13BC0A812140446
- generatedChecksum: A36DE7B9F43B4C6E97A0DA76C5D379CF
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: mclk.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A36DE7B9F43B4C6E97A0DA76C5D379CF
- generatedChecksum: A67B533E2C6C9C26EB72FEC507486506
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A67B533E2C6C9C26EB72FEC507486506
- generatedChecksum: D598975BB9BE1755990719E95AFD0AC6
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D598975BB9BE1755990719E95AFD0AC6
- generatedChecksum: 6DF86D05F2FDACD9BA8E1E1431C7AA40
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: osc32kctrl.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6DF86D05F2FDACD9BA8E1E1431C7AA40
- generatedChecksum: 38B5D972B2BEC6F94D61D3D87AD0976B
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: oscctrl.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 38B5D972B2BEC6F94D61D3D87AD0976B
- generatedChecksum: 4240B19072DD5DDE7C23220C62DBE7E4
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4240B19072DD5DDE7C23220C62DBE7E4
- generatedChecksum: BB4FAC4F00C0D5A94EC40CE92DE7B515
  logicalPath: config\sam_l22_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: BB4FAC4F00C0D5A94EC40CE92DE7B515
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_l22_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config\sam_l22_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: E94C2F2827F3CB08C565ADF200C747B6
  logicalPath: config\sam_l22_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: E94C2F2827F3CB08C565ADF200C747B6
- generatedChecksum: 2C6F9BA1BFA523200ED784A7D4FC3C81
  logicalPath: config\sam_l22_xpro\peripheral\pm
  name: plib_pm.h
  physicalPath: peripheral\pm
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C6F9BA1BFA523200ED784A7D4FC3C81
- generatedChecksum: 7A12D7C361B434548815CB1038486F76
  logicalPath: config\sam_l22_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A12D7C361B434548815CB1038486F76
- generatedChecksum: 988EE410EF19CEC0CB6A4F1CD49CB26D
  logicalPath: config\sam_l22_xpro\peripheral\rtc
  name: plib_rtc.h
  physicalPath: peripheral\rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 988EE410EF19CEC0CB6A4F1CD49CB26D
- generatedChecksum: 9E847139EB4A35248CEAA3CF830D18DD
  logicalPath: config\sam_l22_xpro\peripheral\sercom\usart
  name: plib_sercom0_usart.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E847139EB4A35248CEAA3CF830D18DD
- generatedChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
  logicalPath: config\sam_l22_xpro\peripheral\sercom\usart
  name: plib_sercom_usart_common.h
  physicalPath: peripheral\sercom\usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 925FCFFDB3C2D6B21726F0B97CDA821B
- generatedChecksum: 81FA3D9CA4BF1F9415B27BD7420F1C67
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 81FA3D9CA4BF1F9415B27BD7420F1C67
- generatedChecksum: F7883F507D16FF18EEC121A06540040E
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F7883F507D16FF18EEC121A06540040E
- generatedChecksum: 7AD17BAB835D4754C4109543ED6226F2
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7AD17BAB835D4754C4109543ED6226F2
- generatedChecksum: F054CB8BA339746231B8A40A587478DB
  logicalPath: config\sam_l22_xpro\touch
  name: qtm_acq_saml22_0x0028_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: F054CB8BA339746231B8A40A587478DB
- generatedChecksum: 7DEFA02F559ACE61891DB528BF24E326
  logicalPath: config\sam_l22_xpro\touch
  name: qtm_common_components_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DEFA02F559ACE61891DB528BF24E326
- generatedChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
  logicalPath: config\sam_l22_xpro\touch
  name: qtm_freq_hop_auto_0x0004_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D97AA6DCD7F4BB3C4582D995C98D84B
- generatedChecksum: FB86752FE87F6FFC05CA323960F53142
  logicalPath: config\sam_l22_xpro\touch
  name: qtm_scroller_0x000b_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: FB86752FE87F6FFC05CA323960F53142
- generatedChecksum: B40B26CBF970F40A2CB63C74002B65D4
  logicalPath: config\sam_l22_xpro\touch
  name: qtm_touch_key_0x0002_api.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: B40B26CBF970F40A2CB63C74002B65D4
- generatedChecksum: D25347BD649CE93BCB722FE167176E28
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D25347BD649CE93BCB722FE167176E28
- generatedChecksum: B4A6CDCFFFC075105AADA04009043F2A
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B4A6CDCFFFC075105AADA04009043F2A
- generatedChecksum: 76FC54B61247D69D9C6FE429C8CA4030
  logicalPath: packs\ATSAML22N18A_DFP\pio
  name: saml22n18a.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 76FC54B61247D69D9C6FE429C8CA4030
- generatedChecksum: 618202F63D5C9303EB82CBE70CD05ACB
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 618202F63D5C9303EB82CBE70CD05ACB
- generatedChecksum: BB28ECC8F5E90CBC56689254690F9B16
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: slcd.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BB28ECC8F5E90CBC56689254690F9B16
- generatedChecksum: E553918BB0E7E34CA2F610ACA5D5D196
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: supc.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E553918BB0E7E34CA2F610ACA5D5D196
- generatedChecksum: 0C37B0B2DCDA0C030A07E0C2510EE161
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0C37B0B2DCDA0C030A07E0C2510EE161
- generatedChecksum: EFAAFD1527EE764661F6335B2C138C27
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: EFAAFD1527EE764661F6335B2C138C27
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_l22_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 3701E6B885C1FEB37892DC9F3F471B44
  logicalPath: config\sam_l22_xpro\touch
  name: touch.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 3701E6B885C1FEB37892DC9F3F471B44
- generatedChecksum: 15D9F79B9E1A558CC73876967D1F4A02
  logicalPath: config\sam_l22_xpro\touch
  name: touch_api_ptc.h
  physicalPath: touch
  security: NON_SECURE
  type: HEADER
  userChecksum: 15D9F79B9E1A558CC73876967D1F4A02
- generatedChecksum: 385AF708E41EEB807A3A7EF39E406F64
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: trng.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 385AF708E41EEB807A3A7EF39E406F64
- generatedChecksum: 8682D761037ACFDDE97169197CDDFB5F
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 8682D761037ACFDDE97169197CDDFB5F
- generatedChecksum: 7112AF260A2C6361AEB0A110C67B5968
  logicalPath: packs\ATSAML22N18A_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAML22N18A_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7112AF260A2C6361AEB0A110C67B5968
- generatedChecksum: 0339977513D812C4EFDA52AA75161A39
  logicalPath: config\sam_l22_xpro
  name: ATSAML22N18A.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 0339977513D812C4EFDA52AA75161A39
format_version: v1.0
libraries:
- name: qtm_acq_saml22_0x0028.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_touch_key_cm0p_0x0002.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_scroller_cm0p_0x000b.X.a
  path: /touch/lib/
  security: NON_SECURE
- name: qtm_freq_hop_auto_cm0p_0x0004.X.a
  path: /touch/lib/
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_l22_xpro;../src/packs/ATSAML22N18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_l22_xpro;../src/packs/ATSAML22N18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
