configName: sam_l22_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAML22N18A
projectName: ''
settings:
  PackageFilter: bsp;core;csp;quick_docs;touch;touch_apps;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML22_DFP\3.5.68\atdf\ATSAML22N18A.atdf
